name: musca.se
repository: 'musca/musca.github.com'
gems:
  - jekyll-feed
  - jekyll-github-metadata
markdown: kramdown
highlighter: rouge
description: "Oskar Engdahl´s home on the Web"
url: 'http://oskarengdahl.com'
excerpt_separator: <!--more-->
exclude: [
  "CNAME",
  "src", 
  "node_modules", 
  "gulpfile.js", 
  "package.json", 
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "npm-debug.log"
]
production_url: 'http://oskarengdahl.com'
collections:
   projects:
     output: true
defaults:
 - scope:
     type: projects
   values:
     layout: project
     css: main
     js: main